version: '3.1'

services:
  base:
    build:
      context: .
      dockerfile: ./docker/base.Dockerfile
    image: mockystr/docker-tp-aiomicro-base
  async_orm:
    build:
      context: .
      dockerfile: ./docker/async_orm.Dockerfile
    image: mockystr/docker-tp-aiomicro-orm
  aioserver:
    restart: always
    build:
      context: .
      dockerfile: ./docker/aioserver.Dockerfile
    image: mockystr/docker-tp-aiomicro-aioserver
    ports:
      - 12345:8080
  aioauth:
    restart: always
    build:
      context: .
      dockerfile: ./docker/aioauth.Dockerfile
    image: mockystr/docker-tp-aiomicro-auth
  crawler:
    restart: always
    build:
      context: .
      dockerfile: ./docker/crawler.Dockerfile
    image: mockystr/docker-tp-aiomicro-crawler

#  Queues
  rmq:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

#  Databases
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: emirnavruzov
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: tp_aiomicro
  es:
    image: elasticsearch:7.0.0
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200



# когда я называл сервисы rabbitmq и elasticsearch и создавал перменные окружения
# ENV HOST_RABBIMQ=rabbitmq то почему-то при попытке в контейнере найти переменную окружения
# вместо получения строки он пытался ее выполнить зачем-то
# как это исправить правильно? я просто перемеиновал сервисы, чтоб они не совспадали с командами