apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tp-aiomicro
resources:
- configs/cm.yaml
- depl/orm.yaml
- rabbit.yaml
namePrefix: ${PROJECT_NAME}-
commonLabels:
  app.kubernetes.io/instance: ${PROJECT_NAME}
