apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tp-aiomicro
resources:
- configs/cm.yaml
- depl/orm.yaml
- depl/api.yaml
- api-ingress.yaml
- api-service.yaml
- depl/auth.yaml
- depl/crawler.yaml
- rabbit.yaml
#- es.yaml
namePrefix: ${PROJECT_NAME}-
commonLabels:
  app.kubernetes.io/instance: ${PROJECT_NAME}
