apiVersion: v1
kind: ConfigMap
metadata:
  name: config-environ
  labels:
    app.kubernetes.io/name: config-environ
data:
  POSTGRES_HOST_DB: "64.227.120.20"
  HOST_RABBITMQ: "tp-aiomicro-rabbit-master"
  HOST_ES: "tp-aiomicro-es-master"