apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: mockystr/docker-tp-aiomicro-aioserver
          envFrom:
            - configMapRef:
                name: config-environ
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
