apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
    spec:
      containers:
        - name: auth
          image: mockystr/docker-tp-aiomicro-auth
          envFrom:
            - configMapRef:
                name: config-environ
#          ports:
#            - name: http
#              containerPort: 8080
#              protocol: TCP
          resources: {}
