apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app.kubernetes.io/name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crawler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crawler
    spec:
      containers:
        - name: crawler
          image: mockystr/docker-tp-aiomicro-crawler
          envFrom:
            - configMapRef:
                name: config-environ
#          ports:
#            - name: http
#              containerPort: 8080
#              protocol: TCP
          resources: {}
