apiVersion: batch/v1
kind: Job
metadata:
  namespace: tp-aiomicro
  name: migrations
  labels:
    app.kubernetes.io/name: migrations
spec:
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: api
          image: mockystr/docker-tp-aiomicro-orm
          envFrom:
            - configMapRef:
                name: config-environ
          resources: {}
